SEARCH_DIR = 'THIS IS YOUR PICS DIRECTORY WHERE AKU AKU WILL TRY TO FIND images'
DB_FILE = SEARCH_DIR[:-5] + 'pics.db' #this is pics db
PART_OF_URL = 'https://walld.net/pics/' #this is where it will be stored on server 
DEBUG = False #do you need pretty debug? set to true if so
DB = 'postgres'
DB_HOST = "blah-blah.org"
DB_NAME = 'MAH-BOYS'
DB_USER_NAME = 'walld_user'
DB_PASSWORD = 'walld_password'
DB_PORT = '5432'